### ISSUE TITLE
ACF Version 5

### ISSUE THREAD

**Issue by lukecav** [DannyvanHolten/acf-gravityforms-add-on#1]
Will this plugin work with version 5 of Advance Custom Fields? 

https://www.advancedcustomfields.com/resources/beta-test-version-5/

**Comment by DannyvanHolten** [comment]
Yes. It already is. I use Advanced Custom Fields Pro which currently is at 5.5.11, and this version is now in beta for the free version of Advanced Custom Fields Pro.

If in any way it seems it won't work. Just contact me and I will edit the plug-in, but I'm pretty certain it already is.
