### ISSUE TITLE
Only echo form ID?

### ISSUE THREAD

**Issue by ThePixelPixie** [DannyvanHolten/acf-gravityforms-add-on#10]
Hi there,
I'm trying to count the number of entries in a particular selected form.  The code I use manually is:

$summary = RGFormsModel::get_form_counts(4);

But if I want to instead echo the count of the form selected, for instance, I've tried:

$sales_form = get_field('associated_order_form');
$summary = RGFormsModel::get_form_counts($sales_form['id']);

and it doesn't work. What am I doing wrong here?

**Comment by ThePixelPixie** [comment]
Bumping since it's been 5 days since I tried asking here...

**Comment by DannyvanHolten** [comment]
I am sorry for the late reaction.  wat is the content of sales_form when your try to dump it?

**Comment by DannyvanHolten** [comment]
I am closing this issue because as far as I know this works, and I didn’t get a reaction.

**Comment by DannyvanHolten** [comment]
I am closing this issue because as far as I know this works, and I didn’t get a reaction.
