### ISSUE TITLE
Feature request: exclude some Gravity Forms by ID

### ISSUE THREAD

**Issue by certainlyakey** [DannyvanHolten/acf-gravityforms-add-on#17]
Thanks for the great plugin! 

I recently had a use case for excluding a certain form by its ID. Would it be possible to add a hook that would allow to filter the Gravity Forms that get into the field values?

**Comment by tlygnersjo** [comment]
+1

I want to do something similar, either include Gravity Forms or exclude. It would be great if there was some sort of hook for this use cases.

Is this possible to solve? @DannyvanHolten

**Comment by DannyvanHolten** [comment]
You mean you want have a checkbox in a certain gravity form to exclude it from the list? I hope you can confirm. I am planning on having another programming session on this plugin this weekend

**Comment by certainlyakey** [comment]
What I meant was just having a hook where you can filter gravity forms shown as the field values. This way we could remove some of the forms from the field output in the admin as well.

**Comment by DannyvanHolten** [comment]
Thanx for the answer :) I will look into it, haven't done WordPress for a couple of months. But creating a hook shouldn't be that difficult.

**Comment by zitrusblau** [comment]
Definitely would be a nice addition.

You could then also check the form settings array and include/exclude by custom form settings or whatever like described here:
https://docs.gravityforms.com/gform_form_settings/
