### ISSUE TITLE
Conflict with GF Survey add-on 

### ISSUE THREAD

**Issue by christiaanstijnen** [DannyvanHolten/acf-gravityforms-add-on#18]
Hi,

First; Very handy plugin, thanks! :)
I do have a small bug, when activating your acf-gravityforms-add-on, the survey add-on from Gravity Forms breaks on the front-end. What happens is that the label is showed, but the html for the field is not showing up. I don't get any console errors ...

Thanks if you have a chance to take a look at it.

**Comment by christiaanstijnen** [comment]
I don't know why, but if I comment out 
`$this->forms = GFAPI::get_forms();`
on line 19 in Notices.php the bug seems to be solved. This public $forms; is not used anyway in notices.php?

**Comment by besimhu** [comment]
This might also be related to GF Coupons field not showing up. The label is there, but field is not appearing.

**Comment by tmdk** [comment]
I'm experiencing similar problems with this plugin in combination with the Pronamic Pay plugin. The Issuer field only shows the field label, not the select element to choose a bank.

Additionally, the Payment Method field is somehow changed from a dropdown to a group of radio buttons. Not sure if this is even related though.

Using gravityforms 2.3.0, Pronamic Pay 4.7.0 and acf-gravityforms-add-on 2.1.0.

**Comment by markhowellsmead** [comment]
Version 1.2.6 is now released.
