### ISSUE TITLE
save selected Form in the Backend

### ISSUE THREAD

**Issue by srueegger** [DannyvanHolten/acf-gravityforms-add-on#2]
Hi - I have a problem with the Plugin.
Is use the latest Wordpress Version (4.7.3) and the latest ACFpro Plugin.
My Problem:
i choose a form, and save the Page. De Edit-Page Reloads every Field is saved, but not the Field for the Forms. Is this a Bug?

**Comment by DannyvanHolten** [comment]
Hey @srueegger. I gues you are using v5.5.11 of the ACF Pro plugin?

**Comment by DannyvanHolten** [comment]
Can you maybe make a screenshot? I can't seem to replicate what you mean.

**Comment by DannyvanHolten** [comment]
Ah, I see now. I will fix this straight away :)

**Comment by DannyvanHolten** [comment]
It was a flaw in the typehinting. I now made sure both are cast as integer values are now cast as integer. I fixed it, and tagged it with 1.1.1

**Comment by srueegger** [comment]
Thank You! :-)
