### ISSUE TITLE
Ability to choose default form?

### ISSUE THREAD

**Issue by andrewdodson14** [DannyvanHolten/acf-gravityforms-add-on#21]
Is there an ability to specify a default form? On the site I'd like to use this on, I'd rather it not be the first form in the list in case my client accidentally forgets to change it. Otherwise, thank you for this plugin!

**Comment by DannyvanHolten** [comment]
I am thinking of creating a checkmark at the specific form you want to add as default. Is that a proper solution for you. I am not really keen on adding a settings pageZ

**Comment by DannyvanHolten** [comment]
I think I will create a hook. Just like for the hiding of forms.
