### ISSUE TITLE
Custom Field checkboxes not populating when multiple selected from form

### ISSUE THREAD

**Issue by lkbarron** [DannyvanHolten/acf-gravityforms-add-on#22]
I have a front-end Gravity form that I want to populate into custom fields for a custom post type, in this instance, called Portfolio...but it's only passing one value, not all selected for the checkbox fields from the form.  I'm furthermore then using that entered data to display via shortcode (or merge tags if needed, but prefer acf shortcode) into the design of that Portfolio item in the front-end. I've been troubleshooting wondering if there's some conflict between plugins as I'm also using Gravity Forms + Custom Post Types plugin, but so far I am not sure yet.  Any idea why this might be happening and/or how to fix it?

**Comment by markhowellsmead** [comment]
This is unfortunately outside the scope of this plugin. I would recommend that you pass your enquiry to Gravity Forms directly.
