### ISSUE TITLE
Conflict with Gravity Forms Signature Add-On

### ISSUE THREAD

**Issue by joshlewis** [DannyvanHolten/acf-gravityforms-add-on#24]
Hi Danny,

My report is extremely similar to issue #23, and I really liked his text, so I'm going to reuse it if that's all right.

Your plugin is awesome, but I've run into a conflict with it.

I'm using the Gravity Forms Signature Add-On (https://www.gravityforms.com/add-ons/signature/) and when I install the ACF/GF Add-On the signature input field no longer appears in my forms. When I disable AFC/GF it appears again. More specifically, the label for the field appears, but the actual signature box does not.

I understand that you may not guarantee performance with optional add-ons, but I thought I'd let you know about the conflict, as it took me awhile to suss it out.

Thanks,
Josh

**Comment by lkbarron** [comment]
I'm having the same issue and just troubleshooted the same problem.  Might be beneficial to having it working soon especially with all the GDPR laws coming up...thanks!

**Comment by rk** [comment]
We had to replace this field with Number fields to get the signature fields working.

The strangest thing is, all I did was use the `gravity_form()` method to output the form from the ID and it worked. The conflict must be from somewhere else within the plugin (a hook maybe).

**Comment by lkbarron** [comment]
Weird...thanks for looking into!  So, do I need to do something, or is this
included with yesterdays' update? I don't see the update pushed out yet to
my WP Dashboard, but hopefully soon.  I could manually do it too, but
easier to just wait I suppose.  Site I'm working on is still in DEV...but
would be cool to have it working :)

Thanks!


[image: photo]
*Laurie Kerns Barron*
WordPress Developer, Simply Styled Sites

317-408-2302 | laurie@simplystyledsites.com

www.simplystyledsites.com | Skype: lauriebarron <#>
<http://facebook.com/lkbarron> <http://linkedin.com/in/lauriekbarron/>
<http://twitter.com/lauriekbarron>
Get your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>

**Comment by alexanderkladov** [comment]
Found this thread too late.. Just spent 2h trying to figure out why on earth the signature drawing area stopped showing up on my forms. Until I disabled this add-on and everything went back to normal. So clearly this is still a problem on latest GF + latest ACF GF add-on versions..

Such a shame. Awesome plugin otherwise, but I can't have it break my Signature fields, as without them the forms are useless.

Just thought I'd post it here, in case anyone else is wondering why their Signature field stopped working.

**Comment by markhowellsmead** [comment]
@joshlewis @lkbarron @rk @alexanderkladov @n8kowald I have manually merged in a number of pending code amendments. Due to the age of the change requests, I would greatly appreciate it if you could install 1.2.5 from Github and let me know if the issues mentioned here are resolved. Many thanks!

**Comment by markhowellsmead** [comment]
Version 1.2.6 is now released.
