### ISSUE TITLE
Co-owner

### ISSUE THREAD

**Issue by DannyvanHolten** [DannyvanHolten/acf-gravityforms-add-on#27]
Hey guys. Since I am not working with WordPress anymore and I've switched to React for building websites at another company. I wanted to keep my plug-ins up-to-date but I am struggling to do so. Because of not having PHP, WordPress & several plugin licences but also because of motivation.

I'm therefore looking for (an)other person(s) who wants to improve, maintain & co-own the plugin. Please let me know if you're interested in this. I would like to keep the code quality high, so I will still review code together with you :)

Hope to find someone so we can get this plugin up-to-date again!

**Comment by spivurno** [comment]
Hey Danny, I'm the developer of [Gravity Perks](http://gravitywiz.com) (by Gravity Wiz). I'm interested. What's the best way to chat?

**Comment by markhowellsmead** [comment]
I now have co-ownership. Version 1.2.6 is now released.
