### ISSUE TITLE
Doesn't save values when added to ACF options pages

### ISSUE THREAD

**Issue by badfeather** [DannyvanHolten/acf-gravityforms-add-on#31]
I've added a form field to an [options page](https://www.advancedcustomfields.com/resources/options-page/), and it looks like nothing gets saved to the site options. When using AFC on options pages, the standard behavior is to create a site option with a `'options_'` prefix before the field key, e.g. if your field key was `'gravity_form'`, it creates a site option with the key `'options_gravity_form'`. Using this plugin, no options get saved to the database.

Thanks for making and maintaining this plugin, BTW. It's very handy, and works well.

**Comment by markhowellsmead** [comment]
@badfeather This plugin is for use with the Gravity Forms plugin. Is the issue you're encountering related to a Gravity Forms implementation?

**Comment by markhowellsmead** [comment]
No response since January.
