### ISSUE TITLE
Conflict with Gravity Forms Range Slider

### ISSUE THREAD

**Issue by thesublimeobject** [DannyvanHolten/acf-gravityforms-add-on#33]
Plugin Website: https://www.gfrangeslider.com/

**Issue**
When the GF/ACF plugin is activated, the range slider fields do not render. When deactivated, they work again. I went through the GF/ACF and tried to debug it a bit myself: the GF/ACF plugin does not cause a conflict in any place that i can see _except for_ the notifications class (Notices.php). I'm not exactly sure what part of it is causing the conflict, but it's a pretty small file? For right now, I just commented out the `$this->addNotices();` from the class constructor, but this is obviously not a great long-term solution, so I was hoping that something could be done and integrated into the plugin for posterity.

Please let me know if you need any more information; happy to provide whatever you need and/or help in any way. Thanks!

**Comment by RupW** [comment]
There are two PRs that change addNotices to fix this, yes: #29 and #32

**Comment by thesublimeobject** [comment]
@RupW okay, my bad. i searched, but didn't notice those. do you have any idea when these will be merged/released?

**Comment by markhowellsmead** [comment]
I've pinged @DannyvanHolten again and hope to gain access to the repository. Please refer to #29.

**Comment by RupW** [comment]
@thesublimeobject Oops, what I meant was "yes, that's the right fix". Apologies for any misunderstanding! No criticism intended.
