### ISSUE TITLE
Plugin Work With Latest Wordpress Version?

### ISSUE THREAD

**Issue by hotstickybun** [DannyvanHolten/acf-gravityforms-add-on#36]
Enabled the plugin after downloading it but when I select the forms field in ACF nothing is populating or showing up?  Based on the old Wordpress Screenshots on the repository there should be a selection field correct?  This doesn't appear for me anymore and don't see any errors in my console./
![noform](https://user-images.githubusercontent.com/26367694/95661134-1cfe8780-0aea-11eb-941d-74265295e4bc.jpg)

**Comment by markhowellsmead** [comment]
This screen is correct. You will be able to select from your Gravity Forms wherever this ACF field group is visible. For example, if the field group is set to appear on a Post edit screen, then you can select a Gravity Form on the Post edit screen, wherever your field “Finished” appears.
