### ISSUE TITLE
Removing form associated with custom post type

### ISSUE THREAD

**Issue by toby1kenobi** [DannyvanHolten/acf-gravityforms-add-on#37]
Great plugin, thanks for this!

I've used it to associate instances of Gravity Forms with instances of a custom post type, which works well. 

However, if I want to remove a previously selected form from a custom post it seems to work (if I return to edit the custom post the form is no longer selected) but when I query my custom posts in PHP and do a get_field(my_form_key) on them the original form ID still seems to be returned.

Have I omitted to do something necessary?

**Comment by markhowellsmead** [comment]
1. Is the key (`my_form_key`) unique across all field groups which are assigned to the Post? 
2. Are you explicitly passing the Post ID to `get_field`?

**Comment by markhowellsmead** [comment]
I've tested this case in an otherwise uncustomized installation and, provided that the option "allow empty" is set on the ACF field, there are no problems. I can only imagine that there are multiple meta entries in your database for the post in question which have the key `my_form_key`.

**Comment by toby1kenobi** [comment]
Thanks for getting back to me so quickly! I think it was something glitchy at my end rather than your plugin, apologies for not discovering that before opening this issue.
