### ISSUE TITLE
Adding gravityforms to graphql

### ISSUE THREAD

**Issue by AlexMorrisonDev716** [DannyvanHolten/acf-gravityforms-add-on#39]
Hi! Love the plugin, but would it be possible to make the plugin queryable via graphql? This would come in handy as more sites move to a headless approach. Cheers!

**Comment by markhowellsmead** [comment]
The plug-in allows a user to add a field to an ACF field group. What would you want to access using GraphQL?

**Comment by AlexMorrisonDev716** [comment]
Thanks for getting back to me so soon :)

So I'm building a site via gatsby and am leveraging this package: https://github.com/robmarshall/gatsby-gravityforms-component

What I'm trying to accomplish is expose the ID of the form I select in your plugin so I can pass that down as a prop to the package above. I tried your plugin to make it easier for a user to select a form instead of manually entering the ID into a text/number field.

When I tried your plugin I didn't see a toggle to "Show in GraphQL" and resorted to a number field. Screenshot attached for what that looks like.

<img width="1070" alt="Screen Shot 2021-04-14 at 4 06 12 PM" src="https://user-images.githubusercontent.com/12971783/114772602-fdb41180-9d3b-11eb-8b14-ec2b2676aae6.png">

**Comment by RupW** [comment]
It looks like the 'Show in GraphQL' button actually comes from this plugin: https://github.com/wp-graphql/wp-graphql-acf

They list the fields they support, so I'd guess support needs to be added at their end not here? If we would need to make changes here, can you link us to (or ask them for) documentation of what we'd need to do?
