### ISSUE TITLE
Rename Forms into Gravity Forms

### ISSUE THREAD

**Issue by WarenGonzaga** [DannyvanHolten/acf-gravityforms-add-on#41]
It is better if you name it Gravity Forms in field types instead of just forms. 
The reason why is that it conflicts with ACF Extended. See the screenshot below.
![image](https://user-images.githubusercontent.com/15052701/133231311-39e62c39-c155-4c17-b181-de69aebd68dd.png)

You can also implement a way to detect ACF Extended and it will rename itself to Gravity Forms. This will help us to avoid confusion.

**Comment by markhowellsmead** [comment]
Thanks for the suggestion. This is now pushed in version 1.2.9.

**Comment by WarenGonzaga** [comment]
> Thanks for the suggestion. This is now pushed in version 1.2.9.

that was fast!
