### ISSUE TITLE
Sorting of form list in dropdown

### ISSUE THREAD

**Issue by heidimark** [DannyvanHolten/acf-gravityforms-add-on#47]
It would be nice if the list of forms in the dropdown were sorted by title rather than ID.

/resources/Field.php
line 97

Replace
$this->forms = GFAPI::get_forms();

With
$this->forms = GFAPI::get_forms(true,false,'title');

**Comment by markhowellsmead** [comment]
Resolved in 1.3.0.

**Comment by heidimark** [comment]
Wow, that was fast! Thank you!!!
