### ISSUE TITLE
Different input method for "Select multiple values?" option

### ISSUE THREAD

**Issue by cbirdsong** [DannyvanHolten/acf-gravityforms-add-on#50]
`<select multiple>`:
- requires scrolling to see more than 3-4 options
- requires users to know a keyboard shortcut to select non-sequential options
- makes it very easy to clear the current value through accidental input
- is [not recommended by accessibility experts](https://webaim.org/techniques/forms/controls#select) 

Could it be switched to a simple checkbox list?

**Comment by markhowellsmead** [comment]
This has nothing to do with the plugin. Please refer your question to the support forums at advancedcustomfields.com.
