### ISSUE TITLE
Fatal Error on latest update

### ISSUE THREAD

**Issue by ste5en** [DannyvanHolten/acf-gravityforms-add-on#51]
The latest update added `require __DIR__ . '/platform_check.php';` to autoload_real.php on line 25, but there isn't a platform_check.php file to load. Commenting out that line fixed problems as near as I can tell.

**Comment by azakaryan-godaddy** [comment]
same

**Comment by markhowellsmead** [comment]
On it...

**Comment by markhowellsmead** [comment]
Please try 1.3.1, just published.

**Comment by markhowellsmead** [comment]
Updates Composer config to remove platform check. Error no longer evident.

**Comment by azakaryan-godaddy** [comment]
Thank you! Confirmed that fixed it for us.

**Comment by ste5en** [comment]
Also confirmed! Thanks!
