### ISSUE TITLE
Fatal error after update

### ISSUE THREAD

**Issue by resqonline** [DannyvanHolten/acf-gravityforms-add-on#52]
Hey, my client's site crashed because of this:
`PHP Fatal error:  require(): Failed opening required '/var/www/html/wp-content/plugins/acf-gravityforms-add-on/vendor/composer/platform_check.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/acf-gravityforms-add-on/vendor/composer/autoload_real.php on line 25`
all plugins are on latest version

**Comment by codepuncher** [comment]
@resqonline update to the latest version 1.3.1

**Comment by markhowellsmead** [comment]
This bug was resolved in plugin version 1.3.1.
