### ISSUE TITLE
Make forms appear in repeater

### ISSUE THREAD

**Issue by scottdigitalco** [DannyvanHolten/acf-gravityforms-add-on#53]
I'm trying to make forms appear in a repeater. When I use the code:

$form_id = get_field('my-form');
gravity_form($form_id);

I just get the error "Oops! We could not locate your form."

I have replace 'my-form' with the right custom field. Is this a known issue?

**Comment by markhowellsmead** [comment]
That isn't part of the functionality of the plugin. What is the value of `$form_id`?

**Comment by scottdigitalco** [comment]
OK - that explains why it doesn't work! Which is fine as I can stop checking that I've done something wrong.

The repeater ID is 'project_challenge_forms' and the form field ID within that is 'form', so I'm using 'project_challenge_forms_form' for the ID.

**Comment by markhowellsmead** [comment]
I’d recommend that you check the ACF documentation and request support through the ACF forums.
