### ISSUE TITLE
WPGraphQL integration

### ISSUE THREAD

**Issue by Ririshi** [DannyvanHolten/acf-gravityforms-add-on#54]
In my projects, I'm using [WPGraphQL](https://github.com/wp-graphql/wp-graphql) to query data from WP as a headless CMS. With this, I use ACF and Gravity Forms. There are integration plugins that make it possible to query [ACF fields](https://github.com/wp-graphql/wp-graphql-acf) and [GF forms](https://github.com/harness-software/wp-graphql-gravity-forms) through WPGraphQL. This plugin handily provides the bridge between ACF and GF, but sadly, the field added by this plugin does not show up in the WPGraphQL schema. It would be very nice if this plugin could add support for this, or if a separate plugin would be created that would bridge the gap.

There is an open issue on the WPGraphQL for ACF repo (https://github.com/wp-graphql/wp-graphql-acf/issues/249) that considers a similar issue. It seems like the effort to allow ACF extensions to work with WPGraphQL for ACF has stopped a while ago, but I still hope it would be possible to add support, potentially with some help from the WPGraphQL team.

**Comment by markhowellsmead** [comment]
This plugin supports the standard functionality provided by ACF. It is not possible to add specific support for other third-party solutions. The third-party solution should endeavour to support any custom field types registered through the standard ACF functionality.

**Comment by Ririshi** [comment]
Thanks for the quick reply. I'll see if I can get some support from the WPGraphQL for ACF devs.
