### ISSUE TITLE
Multiple choices select does not populate multiple choices ACF field values

### ISSUE THREAD

**Issue by n3storm** [DannyvanHolten/acf-gravityforms-add-on#57]
We create a multiple choices field in Gravity:

1: Fuu
2: Faa
3: Foo

We create a multiple choices field in ACF for same content type:

1: Fuu
2: Faa
3: Foo

When selected any of the values in Gravity Form let's say 1, 3, only first one is stored in ACF field (1.) In case of 2, 3, then only 2 value is stored in ACF field.

Is this related or even the same as #22 ? Why is this issue not in the scope of acf-gravitforms-add-on plugin? (we are paid customers)

**Comment by markhowellsmead** [comment]
Thank you for your message. My plugin is not provided by Gravity Forms, it's a separate solution. As such, I do not offer paid support, and the issues relating to functionality not provided by my plugin are not within its scope. Please contact Gravity Forms or ACF Support with support requests for the issue you raise.
