### ISSUE TITLE
Multi-select form - Bug on selection

### ISSUE THREAD

**Issue by ronalfy** [DannyvanHolten/acf-gravityforms-add-on#6]
When you have a multi-select form, and you have `allow_null` set to true, you can lose a form output if you happen to select the first item in the dropdown. 

I've attached a video of this occurring. Note the array index. 

[acf-gf-save-bug.mp4.zip](https://github.com/DannyvanHolten/acf-gravityforms-add-on/files/1039385/acf-gf-save-bug.mp4.zip)

**Comment by ronalfy** [comment]
I'd be willing to submit a PR for this.

**Comment by DannyvanHolten** [comment]
I see the video, but I cannot see what is different on the front-end. The only item you lose is - Select a form - right? Or am I missing something.

**Comment by ronalfy** [comment]
The bug is a fairly easy to reproduce. The issue is that one of the choices is stripped when selecting a null value. 

For example, if you have a form with 3 items, and you select all items plus the null value, one of the values saved is removed.

**Comment by DannyvanHolten** [comment]
Ah, so it strips the last value? If you want to make a PR that would be great :) If you need or wish any help I can help you out.

**Comment by DannyvanHolten** [comment]
Hey @ronalfy have you had any time to fix this? Otherwise I will start working on it somewhere this weekend.

**Comment by ronalfy** [comment]
I have not! Go for it and if you can't get to it, I'll try to do it early next week.

**Comment by DannyvanHolten** [comment]
Solved in 1.2.1 :) Thanx!
